# Generated by Django 5.0.7 on 2024-07-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='avtar',
            new_name='avatar',
        ),
    ]
